name: main

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: tree-sitter/setup-action@v2

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: zig build test
        run: zig build test --summary all

      - name: test-patches.zig
        run: zig run script/test-patches.zig
