name: main

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # TODO os: [ubuntu-22.04, macos-latest, windows-latest]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: tree-sitter/setup-action@v2

      - uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: zig build test
        run: zig build test --summary all
